/**
 * Edge-safe harness stat slice for `app/opengraph-image.tsx`.
 *
 * Generated by `npm run sync-harness-counts` — do not edit by hand.
 * Full registry-derived stats live in `harness.ts`.
 */
export const HARNESS_COUNTS = {
	skillCount: 161,
	serviceRouteCount: 27,
	cliCount: 24,
	mcpServerCount: 39,
} as const;
